### ISSUE TITLE
choice of distributed persistent store

### ISSUE THREAD

**Issue by irfanurrehman** [dhilipkumars/MrRedis#1]
I think comparison wise consul gets more point on etcd, for additional features like multiple data centre awareness and better service discovery mechanisms (among the comparison of zookeeper, etcd and consul). but what I found missing is the tree like construct for node values,  and watches. Watches might be important for our implementation. Or may be I did not read about it completely.

We can discuss further and conclude.
As of now etcd looks ok for our usage; but if we need service discovery also in future consul might be the right choice.
The API for both are simple and similar to use in go.. :-)

**Comment by dhilipkumars** [comment]
Hi Irfan, 

Thanks for looking it up.  I have updated some architectural thoughts regarding the storage layer in the 'master' branch.  Please check it out.

I think it might not become completely unreasonable for us to even consider databases like `MySQL` or similar RDBMS in the future. 

We might **have** to answer queries like below

```
Query 1: Select all the Service Instances created by User = X
Query 2: Select all the Procs which runs on Ubuntu Trusty Mesos-Slave
etc
```

Anyways i feel the same too `etcd` is more than sufficient for our current scope,  but the 'store' package should be implemented in such a way that we should be able to add support for other database / KV Store in the future. 

Closing it for now.  Feel free to re-open this issue.
