### ISSUE TITLE
Consider supporting Zookeeper in addition to Etcd

### ISSUE THREAD

**Issue by SEJeff** [dhilipkumars/MrRedis#17]
Some users don't currently use etcd and would prefer to stick with the battletested Zookeeper, which Mesos already relies upon. Please consider dropping etcd as a hard requirement so it is easier to setup and use Mr Redis.

**Comment by dhilipkumars** [comment]
Agreed.  We will start working on this as soon as possible.  It should'nt be very hard

**Comment by SEJeff** [comment]
@dhilipkumars given that zookeeper is a requirement of running Mesos, I think this would make adoption a bit easier for some users. Thanks!

**Comment by itsjustcon** [comment]
+1

**Comment by nagas** [comment]
+1

**Comment by yuusaku-t** [comment]
+1

**Comment by zolech** [comment]
+1

**Comment by liorze** [comment]
+1

**Comment by dhilipkumars** [comment]
Addressed by https://github.com/mesos/mr-redis/pull/45

**Comment by liorze** [comment]
Maybe we should document this feature in the README, or somewhere else, before this issue can be considered fixed?
