### ISSUE TITLE
DC-OS scheduler IP : PORT

### ISSUE THREAD

**Issue by rupamroy** [dhilipkumars/MrRedis#18]
I got a 3 master 6 slaves  coreos DC-OS cluster set up in Amazon. I ran the mr-redis package in dc-os and the mr-redis application is running in marathon. Now from my local machine i want o configure my mrr utility using 

```
mrr init http://<schedulerIP>:<schedulerPORT>
```

But my scheduler is running on a slave machine which does not have a public ip , also since it is running with NETWORK=HOST , it cannot be reached through the public slave IP. How can I reach the scheduler.

**Comment by dhilipkumars** [comment]
As you have mentioned that its a marathon application, did you try endpoint exposed by mesos-dns ?

**Comment by dhilipkumars** [comment]
Hi @rupamroy ,

I would recommend try the below (probably from the node where mrredis.mesos is reachable)

```
$curl -X "POST" mrredis.mesos:5656/v1/CREATE/TestInstance/100/1/3 -v
```

or 

```
$mrr init http://mrredis.mesos:5656
```

Closing the issue.  Please feel free to re-open the issue, if not solved.
