### ISSUE TITLE
Decide on Opensource Licence

### ISSUE THREAD

**Issue by dhilipkumars** [dhilipkumars/MrRedis#2]
@SrinivasChilveri @irfanurrehman 

We need to decide on which opensource Licence we should use for this project. 
- Redis uses : Three clause BSD license
- Mesos uses :  Apache License

should we stick to one of the above as this project is based out of both of them put together or is there a better Opensource Licence we should consider.

Please share your suggestions.

**Comment by irfanurrehman** [comment]
I think the Apache License is best in terms of ability to users to adopt the code.
My suggestions would be Apache.. :-)

**Comment by dhilipkumars** [comment]
Thanks Irfan
Okay Apache 2.0 its then.
