### ISSUE TITLE
about coding conventions

### ISSUE THREAD

**Issue by irfanurrehman** [dhilipkumars/MrRedis#3]
@Dhilip-Kumar-S; I just saw some code that u updated, and do not see consistency in terms of naming conventions.
Lets stick to common go conventions and some suggestions as below:
- No all caps naming except for constants
- Follow golangs standard in terms of naming structures and member
       if the name starts from caps, then it is public
- packages to be named with all small letters or as the first letter caps, if the name consists of 2 words
- names to be unambiguous and not too long at the same time
       for example I saw,you used "cli" for etcd client package, let it be "client" as cli certainly have a very common different meaning and infact we have another folder with same name.
  @Dhilip-Kumar-S @SrinivasChilveri 
- any other suggestions can be added, and lets not have this list as complete now; I will try to update some readme to refer to as we all are just starting to code @this

**Comment by dhilipkumars** [comment]
Totally agreed @irfanurrehman we will stick to standard.  It would be great if you could update an MD file in the main directory of this project 'CodingConventions.md' for the benefit of ourselves and future developers.

**Comment by dhilipkumars** [comment]
Hi @irfanurrehman, Please perform "gofmt" before checking in any code it is a practice we must all follow for code readability and constancy. 

Also add that step in the 'CodingConventions.md' or 'Contribution Guide Lines" Markdown file

**Comment by irfanurrehman** [comment]
totally agree

**Comment by irfanurrehman** [comment]
closing this with updates in readme
