### ISSUE TITLE
mrr commands are giving error

### ISSUE THREAD

**Issue by Shivam38** [dhilipkumars/MrRedis#30]
When I try to run cmd$ mrr create help, It gives below error:
No command 'mrr' found, did you mean:
 Command 'mrd' from package 'mtools' (main)
 Command 'drr' from package 'plastimatch' (universe)
 Command 'mrb' from package 'mrb' (universe)
 Command 'mtr' from package 'mtr' (universe)
 Command 'mtr' from package 'mtr-tiny' (main)
 Command 'mr' from package 'myrepos' (universe)
mrr: command not found

**Comment by dhilipkumars** [comment]
You need to set mrr in the PATH env or you could create an alias for the comamnd.

**Comment by Shivam38** [comment]
thanks @dhilipkumars
