### ISSUE TITLE
Can't run with the Readme's help?

### ISSUE THREAD

**Issue by sunhongtao** [dhilipkumars/MrRedis#47]
The Mrredis framework can add to the mesos,but can't create redis instance?
It is still creating.....

the logs:
2016/10/20 09:59:34 Delta of the previously registered framework is = 9m57.309924424s
2016/10/20 09:59:34 The Framework ID is &FrameworkID{Value:_,XXX_unrecognized:[],} and &FrameworkID{Value:_,XXX_unrecognized:[],}
2016/10/20 09:59:34 MrRedis Registered &FrameworkID{Value:*69065949-4bdb-45d9-973c-525c0d3bb54f-0008,XXX_unrecognized:[],}

the config file is:
{
   "UserName": "ubuntu",
   "FrameworkName": "MrRedis",
   "Master": "20.26.25.148:5050",
   "ExecutorPath": "../exec/MrRedisExecutor",
   "RedisImage": "20.26.25.148:5000/redis:2.8",
   "DBType": "etcd",
   "DBEndPoint": "http://20.26.25.148:2379",
   "LogFile": "stderr",
   "ArtifactIP": "20.26.25.148",
   "ArtifactPort": "5454",
   "HTTPPort": "5656"
 }

**Comment by sunhongtao** [comment]
2016/10/20 10:30:15 Received offer {true 0xc82008d320 1}
2016/10/20 10:30:15 Created 1 master offers for Instance redistyk
2016/10/20 10:30:19 Received Offer with CPU=3.5 MEM=8687 OfferID=69065949-4bdb-45d9-973c-525c0d3bb54f-O127005
2016/10/20 10:30:19 Launched 1 tasks from this offer
2016/10/20 10:30:19 Received Offer with CPU=4 MEM=8815 OfferID=69065949-4bdb-45d9-973c-525c0d3bb54f-O127006
2016/10/20 10:30:19 Launched 0 tasks from this offer
2016/10/20 10:30:19 MrRedis Receives offer
2016/10/20 10:30:19 executor "&ExecutorID{Value:_default,XXX_unrecognized:[],}" lost on slave "&SlaveID{Value:_30e63e99-ba38-4967-a24c-c6a2c73271dd-S0,XXX_unrecognized:[],}" code -1
2016/10/20 10:30:19 MrRedis Task Update received
2016/10/20 10:30:19 Status={redistyk::140e0613-4ea9-4700-6fa8-7db2ffc177e5 TASK_FAILED []}
2016/10/20 10:30:19 Received a Task update from the channel &{redistyk::140e0613-4ea9-4700-6fa8-7db2ffc177e5 TASK_FAILED []}
2016/10/20 10:30:19 Invalid Key /MrRedis/Instances/redistyk/Procs/140e0613-4ea9-4700-6fa8-7db2ffc177e5, Cannot load
2016/10/20 10:30:19 Invalid Key /MrRedis/Instances/redistyk/Procs/, Cannot load
2016/10/20 10:30:19 Task redistyk::140e0613-4ea9-4700-6fa8-7db2ffc177e5 is Failed

**Comment by dhilipkumars** [comment]
From the logs it appears that the Executor is Lost.  Do you know if Docker Daemon is running on the slaves? 

Could you share the Executor Logs please?

**Comment by dhilipkumars** [comment]
Hi @sunhongtao 
Do you still have this problem?

**Comment by sunhongtao** [comment]
Now,I have changed the idea to create the redis cluster. I will continue to study on the mr-redis.
Thanks.
