### ISSUE TITLE
Instances loaded from Zookeeper have no slave records

### ISSUE THREAD

**Issue by eastlondoner** [dhilipkumars/MrRedis#59]
If you save a reds instance to zookeeper with slaves.  Then restart the scheduler. The restarted scheduler doesn't know about the slaves (in status you see Slaves: null)

**Comment by eastlondoner** [comment]
PR for fix https://github.com/mesos/mr-redis/pull/58

**Comment by dhilipkumars** [comment]
PR is now merged
