### ISSUE TITLE
mrr create instance failed error

### ISSUE THREAD

**Issue by zousheng** [dhilipkumars/MrRedis#60]
Hi,

I met an error when setting this up in my mac os, the redis instance status is hang at CREATING state, and the scheduler and mesos-slave gives error as below:

[zou[mac ~/go/src/github.com/mesos/mr-redis/cli]$ curl -X POST "http://mac:5656/v1/CREATE/test7/123/1/0"
Request Accepted, Instance will be created.

check status:
[zou[mac ~/go/src/github.com/mesos/mr-redis/cli]$ curl mac:5656/v1/STATUS/test7
{"Name":"test7","Type":"S","Status":"CREATING","Capacity":123,"Master":null,"Slaves":null}

"2017/05/22 16:25:33 Received a Task update from the channel &{test5::0daf90ff-22a2-4f41-66f0-9d55c6b62e3f TASK_FAILED 6b7a6c11-b4ed-4401-806d-02b7f8e2924c-S0 []}
2017/05/22 16:25:33 Invalid Key /MrRedis/Instances/test5/Procs/0daf90ff-22a2-4f41-66f0-9d55c6b62e3f, Cannot load
2017/05/22 16:25:33 Invalid Key /MrRedis/Instances/test5/Procs/, Cannot load
2017/05/22 16:25:33 Task test5::0daf90ff-22a2-4f41-66f0-9d55c6b62e3f is Failed"

mesos-slave error log:
    E0522 16:25:32.910143 303992832 fetcher.cpp:558] Failed to run mesos-fetcher: Failed to fetch all URIs for container 'e6c52e85-d228-4840-b304-f1a3e2fa964c' with exit status: 256
E0522 16:25:32.910619 305602560 slave.cpp:4650] Container 'e6c52e85-d228-4840-b304-f1a3e2fa964c' for executor 'default' of framework 6b7a6c11-b4ed-4401-806d-02b7f8e2924c-0000 failed to start: Failed to fetch all URIs for container 'e6c52e85-d228-4840-b304-f1a3e2fa964c' with exit status: 256

Would you please give some advice? thanks

**Comment by zousheng** [comment]
Just found the executor configured wrong, thanks

**Comment by jbearor** [comment]
@zousheng I'm experiencing the same issue with master/slaves being null and status stuck on CREATING, can you post your config?

**Comment by zousheng** [comment]
@jbearor the config is  as below,

   {
   "username": "root",
   "frameworkname": "mrredis",
   "master": "10.27.4.231:5050",
   "executorpath": "../exec/MrRedisExecutor",
   "redisimage": "redis:3.0",
   "dbtype": "zookeeper",
   "dbendpoint": "test-ecs-sdb-mesos-master:2181",
   "logfile": "stderr",
   "artifactip": "10.47.70.59",
   "ArtifactPort": "5454",
   "HTTPPort": "5656",
   "mesos_role": "mrredis"
}
and currently I didn't follow up with this issue since Nov 2017, and begin to research k8s. Wish you have have some new findings.
